Keep using nix 2.3
As of recently, Nix 2.4 was released that seems to break cachix's nix action.

```
/usr/bin/sh -c nix path-info --all | grep -v '.drv$' > /tmp/store-path-pre-build
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
Error: Action failed with error: Error: The process '/usr/bin/sh' failed with exit code 1
```

Let's keep using Nix 2.3.x